# Generated by Django 4.1.3 on 2023-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_base', '0002_alter_task_fk_asigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='BN_EXPIRED',
            field=models.BooleanField(default=0),
        ),
    ]
